#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-IPC-ShareLite
Version  : 0.17
Release  : 21
URL      : https://cpan.metacpan.org/authors/id/A/AN/ANDYA/IPC-ShareLite-0.17.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AN/ANDYA/IPC-ShareLite-0.17.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libi/libipc-sharelite-perl/libipc-sharelite-perl_0.17-4.debian.tar.xz
Summary  : Lightweight interface to shared memory
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-IPC-ShareLite-license = %{version}-%{release}
Requires: perl-IPC-ShareLite-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
IPC::ShareLite 0.17
DESCRIPTION
IPC::ShareLite provides a simple interface to shared memory, allowing
data to be efficiently communicated between processes.  Your operating
system must support SysV IPC (shared memory and semaphores) in order to
use this module.
COPYRIGHT & TERMS

%package dev
Summary: dev components for the perl-IPC-ShareLite package.
Group: Development
Provides: perl-IPC-ShareLite-devel = %{version}-%{release}
Requires: perl-IPC-ShareLite = %{version}-%{release}

%description dev
dev components for the perl-IPC-ShareLite package.


%package license
Summary: license components for the perl-IPC-ShareLite package.
Group: Default

%description license
license components for the perl-IPC-ShareLite package.


%package perl
Summary: perl components for the perl-IPC-ShareLite package.
Group: Default
Requires: perl-IPC-ShareLite = %{version}-%{release}

%description perl
perl components for the perl-IPC-ShareLite package.


%prep
%setup -q -n IPC-ShareLite-0.17
cd %{_builddir}
tar xf %{_sourcedir}/libipc-sharelite-perl_0.17-4.debian.tar.xz
cd %{_builddir}/IPC-ShareLite-0.17
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/IPC-ShareLite-0.17/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-IPC-ShareLite
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-IPC-ShareLite/8934406c68d77e1e2b8b6b7b301b19d6b3898eb7
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/IPC::ShareLite.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-IPC-ShareLite/8934406c68d77e1e2b8b6b7b301b19d6b3898eb7

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/IPC/ShareLite.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/IPC/ShareLite/ShareLite.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/IPC/ShareLite/autosplit.ix
